create table if not exists public.privacy_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  request_type text not null check (
    request_type in (
      'confirm_processing',
      'access_data',
      'correct_data',
      'delete_data',
      'privacy_information',
      'revoke_cookie_consent'
    )
  ),
  message text not null,
  confirm_deletion boolean not null default false,
  status text not null default 'pending' check (
    status in ('pending', 'in_review', 'completed', 'rejected')
  ),
  source text not null default 'privacy_page',
  created_at timestamptz not null default timezone('utc', now())
);

comment on table public.privacy_requests is 'Solicitações LGPD recebidas pela página pública de privacidade.';

alter table public.privacy_requests enable row level security;

revoke all on public.privacy_requests from anon;
revoke all on public.privacy_requests from authenticated;
revoke all on public.privacy_requests from public;

grant insert on public.privacy_requests to anon;
grant insert on public.privacy_requests to authenticated;

revoke all on sequence public.privacy_requests_id_seq from anon;
revoke all on sequence public.privacy_requests_id_seq from authenticated;
revoke all on sequence public.privacy_requests_id_seq from public;

grant usage on sequence public.privacy_requests_id_seq to anon;
grant usage on sequence public.privacy_requests_id_seq to authenticated;

drop policy if exists "privacy_requests_insert_public_form" on public.privacy_requests;

create policy "privacy_requests_insert_public_form"
on public.privacy_requests
for insert
to anon, authenticated
with check (
  length(btrim(name)) between 1 and 160
  and length(btrim(email)) between 3 and 255
  and lower(btrim(email)) ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
  and request_type in (
    'confirm_processing',
    'access_data',
    'correct_data',
    'delete_data',
    'privacy_information',
    'revoke_cookie_consent'
  )
  and length(btrim(message)) between 12 and 4000
  and source = 'privacy_page'
  and status = 'pending'
  and (
    (request_type = 'delete_data' and confirm_deletion = true)
    or
    (request_type <> 'delete_data' and confirm_deletion = false)
  )
);

create index if not exists privacy_requests_created_at_idx on public.privacy_requests (created_at desc);
